### ISSUE TITLE
EspTouch V2 not support

### ISSUE THREAD

**Issue by Wingge** [jpoh281/esptouch_smartconfig#10]
EspTouch V2 not support！Do you have any plans to achieve this？Thank you!

**Comment by jpoh281** [comment]
I used to use esp32 machine in the previous company, but I don't use it now.

So there is no immediate update plan, and if you need that function, I would appreciate it if you could send me a PR. 
For espouch_flutter, it seems to support Android v2.
https://pub.dev/packages/esptouch_flutter/versions/1.1.0-androidv2
