### ISSUE TITLE
esptouch_set_timeout

### ISSUE THREAD

**Issue by larinnim** [jpoh281/esptouch_smartconfig#2]
Hi, is there a way to set a connection timeout? Similar to "esptouch_set_timeout" feature? Thank you

**Comment by jpoh281** [comment]
No
but If you need feature I can update

**Comment by larinnim** [comment]
That will be great. A feature that allow us to set a Duration timeout.

**Comment by seikosantana** [comment]
Looks like this is completed but i dont see where i can set the timeout
