### ISSUE TITLE
permission

### ISSUE THREAD

**Issue by Abolfazlnezami2000** [jpoh281/esptouch_smartconfig#8]
hi 
i use this package but not working.
![Screenshot 2021-12-27 101924](https://user-images.githubusercontent.com/56001422/147443245-146607a5-f51b-4ee9-9c00-0fb15df1eb36.png)
i add permission but i call method `EsptouchSmartconfig.wifiData()` show error on consol :
`W/esptouch_smartconfig( 4801): Attempted to get Wi-Fi data that requires additional permission(s).
W/esptouch_smartconfig( 4801): To successfully get WiFi Name or Wi-Fi BSSID starting with Android Q, please ensure your app has the CHANGE_WIFI_STATE and ACCESS_FINE_LOCATION permission.
W/esptouch_smartconfig( 4801): For more information about Wi-Fi Restrictions in Android 10.0 and above, please consult the following link:
W/esptouch_smartconfig( 4801): https://developer.android.com/guide/topics/connectivity/wifi-scan`
and my code :
![Screenshot 2021-12-27 102433](https://user-images.githubusercontent.com/56001422/147443655-494d99d1-eb0d-4a29-857c-2b2ab937b32f.png)
Is there a solution?

**Comment by jpoh281** [comment]
Let me check. Thanks for letting me know.
