### ISSUE TITLE
SSID and BSSID is null when run on IOS

### ISSUE THREAD

**Issue by larryxia-ddl** [jpoh281/esptouch_smartconfig#9]
It works on Android, but not working on IOS.  When run on IOS, the wifiname and bssid is null although the connectionstate is done. Please advise how to fix this issue. I attached my code in below. 

 return FutureBuilder<Map<String, String>?>(
                  future: EsptouchSmartconfig.wifiData(),
                  builder: (context, snapshot) {
                    if (snapshot.connectionState == ConnectionState.done) {
                      return WifiPage(snapshot.data!['wifiName']!, 
                      snapshot.data!['bssid']!);
                    } else
                      return Center(
                        child: CircularProgressIndicator(),
                      );
                  });
            }

**Comment by jpoh281** [comment]
I recommend using the network_info_plus package created by the flutter community.

**Comment by larryxia-ddl** [comment]
I tried network_info_plus, info.getWifiName() return null. My iphone is running on ios15.1

**Comment by larryxia-ddl** [comment]
never mind, their document said it doesn't support ios 14 plus, which need request user's authorization to use location information.

**Comment by jpoh281** [comment]
Ok. Thanks to using my plugin
